Hopwood Optimized Fixed-Base Scalar Multiplication
HorizenOfficial/ginger-lib pull request #129
Opened 2021-10-06 13:04 UTC by 95DDB

Import Hopwood's optimized vbSM gadget as per https://github.com/zcash/zcash/issues/3924 .
Currently performed with incomplete arithmetic

2021-10-06 17:13 UTC, UlrichHaboeck75 requested changes
The checks for exceptions of the mul_bits_fixed_base needs some changes, as described in my inline comments.

2021-10-06 17:13 UTC, UlrichHaboeck75 commented on r1cs/gadgets/std/src/groups/mod.rs
> +///           and must not be equal to {0, p-2, p-1, p, p+1}.
outdated comment, I will change it.

2021-10-06 17:13 UTC, UlrichHaboeck75 commented on r1cs/gadgets/std/src/groups/mod.rs
> +    let two_to_n = two.pow(&[bits_len as u64]);
n is the length of the *padded* bit sequence.

2021-10-06 17:13 UTC, UlrichHaboeck75 commented on r1cs/gadgets/std/src/groups/mod.rs
> +    }
As DDT hopefully informed you, I missed to communicate you a fourth condition:
```
[b_{n-1},...,b_0] = 0 mod p
```

2021-10-06 17:13 UTC, UlrichHaboeck75 commented on r1cs/gadgets/std/src/groups/curves/short_weierstrass/short_weierstrass_jacobian.rs
> +        acc = acc.sub_constant(cs.ns(|| "acc - to_sub"), &to_sub)?;
I suppose sub_constant is safe, i.e. it enforces different x-coordinates?

2021-10-07 08:26 UTC, 95DDB commented on r1cs/gadgets/std/src/groups/curves/short_weierstrass/short_weierstrass_jacobian.rs
> +        acc = acc.sub_constant(cs.ns(|| "acc - to_sub"), &to_sub)?;
Yes. It calls the add_constant which is only in the safe variant

2021-10-07 09:19 UTC, UlrichHaboeck75 approved these changes

2021-10-07 09:43 UTC, merged